### ISSUE TITLE
Unable to connect device

### ISSUE THREAD

**Issue by sebasvisser** [hannesschulze/conecto#8] opened 2019-03-31 20:30 UTC
Nothing happening when I'm trying to add my phone to conecto.
When starting the app from the terminal it shows:

`[INFO 22:29:05.976214] Application.vala:155: Conecto version: 0.1
[INFO 22:29:05.976240] Application.vala:157: Kernel version: 4.15.0-46-generic
[WARNING 22:29:05.999303] Contractor.vala:48: Error: Error opening directory '/home/sebasvisser/.local/share/contractor': No such file or directory
Could not aquire name
`

**Comment by sebasvisser** [comment] 2019-03-31 20:31
And when running with -d parameter:

`sebasvisser@sebasvisser-XPS-13-9360:~$ com.github.hannesschulze.conecto -d
** Message: 22:30:52.988: Conecto.vala:115: Report any issues/bugs you might find to https://github.com/hannesschulze/conecto/issues
[INFO 22:30:52.988515] Application.vala:155: Conecto version: 0.1
[INFO 22:30:52.988556] Application.vala:157: Kernel version: 4.15.0-46-generic
[WARNING 22:30:53.010265] Contractor.vala:48: Error: Error opening directory '/home/sebasvisser/.local/share/contractor': No such file or directory
[DEBUG 22:30:53.010373] DeviceManager.vala:35: Device manager.
[INFO 22:30:53.098090] SMSStoreFactory.vala:30: Using SMSStoreSQLite.
[DEBUG 22:30:53.098319] SMSStoreSQLite.vala:102: Sqlite initialization.
[INFO 22:30:53.101532] ShareHandler.vala:47: Downloads will be saved to /home/sebasvisser/Downloads/Conecto
[INFO 22:30:53.101791] Core.vala:50: Supported interfaces: kdeconnect.notification, kdeconnect.share.request, kdeconnect.telephony, kdeconnect.battery, kdeconnect.ping
[DEBUG 22:30:53.101858] DeviceManager.vala:46: Cache file: /home/sebasvisser/.cache/mconnect/devices
[DEBUG 22:30:53.101909] DeviceManager.vala:60: Try loading devices from device cache /home/sebasvisser/.cache/mconnect/devices
[DEBUG 22:30:53.101953] DeviceManager.vala:76: Error loading cache file: No such file or directory
[DEBUG 22:30:53.102168] Discovery.vala:41: Start listening for new devices at: 0.0.0.0:1714
Could not aquire name
[DEBUG 22:30:53.120787] EContacts.vala:43: Discovered source: 'Personal' with backend: 'local'
[DEBUG 22:30:53.120893] EContacts.vala:59: Adding source: 'Personal'
[DEBUG 22:30:53.166474] EContacts.vala:86: Loading contacts from source: 'Personal'

`

**Comment by kr428** [comment] 2019-04-01 13:56
Same here. Elementary Juno, built from master.

**Comment by ryankugel** [comment] 2019-04-08 04:26
I have this issue as well. 

I manually created the folder ~/.local/share/contractor/ and now the error is gone, but it still can't connect. Prints "Could not acquire name" in the console.

**Comment by igalic** [comment] 2019-04-11 13:02
same issue on my machine…

i checked with [mconnect](https://github.com/kevinselvaprasanna/mconnect) and it's the same issue there, so at least it's not specific to this project

but it might be to our setup??

i've turned off Blokada on my phone, and this is my `iptables-save`:

```iptables
# Generated by iptables-save v1.6.1 on Thu Apr 11 15:00:51 2019
*nat
:PREROUTING ACCEPT [24:28285]
:INPUT ACCEPT [24:28285]
:OUTPUT ACCEPT [970:64829]
:POSTROUTING ACCEPT [970:64829]
COMMIT
# Completed on Thu Apr 11 15:00:51 2019
# Generated by iptables-save v1.6.1 on Thu Apr 11 15:00:51 2019
*filter
:INPUT ACCEPT [36077:102718231]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [36307:6060523]
COMMIT
# Completed on Thu Apr 11 15:00:51 2019
```

**Comment by ryankugel** [comment] 2019-04-11 14:04
I did some digging through the code and found where the issue is. 

In the Conecto.vala activate () method the first line is attempting to clean the Contractor directory:
`Contractor.clean_contractor_directory.begin ();`
I added a line above that creates the directory if it's not already there. I'm not sure why this wasn't already in the code...
`Contractor.create_if_not_exists_contract_dir ();`

Unfortunately the issues I'm having are not just because of the Contractor directory. The "Could not acquire name" is coming from MConnectThread.vala during this line:
`Bus.own_name (BusType.SESSION, "com.github.hannesschulze.conecto", BusNameOwnerFlags.NONE,
        on_bus_aquired,
        () => {},
        () => stderr.printf ("Could not aquire name\n"));`

It appears mconnect is attempting to acquire a name on the bus but that is failing, which isn't allowing mconnect to handle any of the networking? I've never worked on anything with networking so my knowledge is pretty slim on this.

**Comment by hannesschulze** [comment] 2019-04-12 18:49
@ryankugel Thank you very much for looking into this :)

I don't know why there isn't a check for the directory in there - what's really weird is that it worked for me the first time, so I guess it was created somewhere else.

But I really don't know why the name can't be acquired - the code seems fine to me. I'll take another look at this once I have the time

**Comment by ryankugel** [comment] 2019-04-12 19:13
I think it might be an issue on my end, rather than the code. I think there might be some kind of restrictions on my network that aren't allowing for this type of thing to work.

I installed KDE neon on my other computer and tried using KDE Connect, but it was also unable to find my phone on the network. I'll probably have to wait until May when I graduate from school and will actually be able to manage my network.

**Comment by hannesschulze** [comment] 2019-04-28 14:58
I'm closing this now because this particular issue is fixed. Feel free to open another issue for other problems :)

**Closed by hannesschulze** 2019-04-28 14:58 UTC
Labels: In Progress
